"""initial schema

Revision ID: b93b074919d1
Revises: 
Create Date: 2026-10-07 20:28:42.499392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b93b074919d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('operating_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('is_domestic', sa.Boolean(), nullable=False),
    sa.Column('min_ram_gb', sa.Integer(), nullable=False),
    sa.Column('min_cpu_cores', sa.Integer(), nullable=False),
    sa.Column('min_disk_gb', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operating_systems_name'), 'operating_systems', ['name'], unique=True)
    op.create_table('software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('category', sa.Enum('office', 'browser', 'accounting', 'cad', 'graphics', 'communications', 'security', 'utility', 'email', 'media', 'development', 'database', 'pdf', 'remote_access', 'other', name='softwarecategory'), nullable=False),
    sa.Column('is_domestic', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_name'), 'software', ['name'], unique=True)
    op.create_table('compatibility_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.Column('target_os_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('native_ready', 'alternative_available', 'web_alternative', 'blocker', name='compatibilitystatus'), nullable=False),
    sa.Column('analog_name', sa.String(length=255), nullable=True),
    sa.Column('is_blocker', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.ForeignKeyConstraint(['target_os_id'], ['operating_systems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('software_id', 'target_os_id', name='uq_software_os')
    )
    op.create_index(op.f('ix_compatibility_rules_software_id'), 'compatibility_rules', ['software_id'], unique=False)
    op.create_index(op.f('ix_compatibility_rules_target_os_id'), 'compatibility_rules', ['target_os_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'analyst', 'viewer', name='userrole'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('target_os_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['target_os_id'], ['operating_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_sessions_created_at'), 'audit_sessions', ['created_at'], unique=False)
    op.create_table('workstations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_session_id', sa.Integer(), nullable=False),
    sa.Column('workstation_ext_id', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('user_fullname', sa.String(length=255), nullable=True),
    sa.Column('current_os', sa.String(length=100), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('disk_gb', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audit_session_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_session_id', 'workstation_ext_id', name='uq_session_workstation')
    )
    op.create_index(op.f('ix_workstations_audit_session_id'), 'workstations', ['audit_session_id'], unique=False)
    op.create_index(op.f('ix_workstations_department'), 'workstations', ['department'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workstation_id', sa.Integer(), nullable=False),
    sa.Column('target_os_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ready', 'upgrade_required', 'blocked', name='assessmentstatus'), nullable=False),
    sa.Column('wave', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('hardware_issues', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_os_id'], ['operating_systems.id'], ),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_index(op.f('ix_assessments_target_os_id'), 'assessments', ['target_os_id'], unique=False)
    op.create_index(op.f('ix_assessments_wave'), 'assessments', ['wave'], unique=False)
    op.create_index(op.f('ix_assessments_workstation_id'), 'assessments', ['workstation_id'], unique=True)
    op.create_table('workstation_software',
    sa.Column('workstation_id', sa.Integer(), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workstation_id', 'software_id')
    )
    op.create_table('assessment_blockers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('hardware', 'software', 'os', name='blockerseverity'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['software_id'], ['software.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_blockers_assessment_id'), 'assessment_blockers', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_blockers_assessment_id'), table_name='assessment_blockers')
    op.drop_table('assessment_blockers')
    op.drop_table('workstation_software')
    op.drop_index(op.f('ix_assessments_workstation_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_wave'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_target_os_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_workstations_department'), table_name='workstations')
    op.drop_index(op.f('ix_workstations_audit_session_id'), table_name='workstations')
    op.drop_table('workstations')
    op.drop_index(op.f('ix_audit_sessions_created_at'), table_name='audit_sessions')
    op.drop_table('audit_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_compatibility_rules_target_os_id'), table_name='compatibility_rules')
    op.drop_index(op.f('ix_compatibility_rules_software_id'), table_name='compatibility_rules')
    op.drop_table('compatibility_rules')
    op.drop_index(op.f('ix_software_name'), table_name='software')
    op.drop_table('software')
    op.drop_index(op.f('ix_operating_systems_name'), table_name='operating_systems')
    op.drop_table('operating_systems')
    op.drop_table('departments')
    # ### end Alembic commands ###

    # ─── Явно удаляем Enum-типы (иначе PostgreSQL их не удалит) ───
    op.execute("DROP TYPE IF EXISTS softwarecategory")
    op.execute("DROP TYPE IF EXISTS userrole")
    op.execute("DROP TYPE IF EXISTS compatibilitystatus")
    op.execute("DROP TYPE IF EXISTS assessmentstatus")
    op.execute("DROP TYPE IF EXISTS blockerseverity")
